name: Playwright Tests

on:
  # 1) Manual trigger
  workflow_dispatch:

  # 2) Automatically run tests on push
  push:
    branches: [ main, master ]

  # 3) Automatically run tests on pull requests
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Use Node.js LTS
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # # Step 6: (Optional) Upload test report as artifact
      # - name: Upload Playwright report
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
